-- AlterTable
ALTER TABLE "Match" ALTER COLUMN "status" SET DEFAULT E'ACTIVE';
ALTER TABLE "Match" ALTER COLUMN "dt_created" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Match" ALTER COLUMN "dt_updated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "dt_created" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Profile" ALTER COLUMN "dt_updated" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Profile" ALTER COLUMN "role" SET DEFAULT E'VOLUNTEER';
ALTER TABLE "Profile" ALTER COLUMN "environ" SET DEFAULT E'dev';

-- AlterTable
ALTER TABLE "Profile_Interest" ALTER COLUMN "dt_created" SET DEFAULT CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE "Match_Note" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "match_id" INT8 NOT NULL,
    "note" STRING,
    "dt_created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dt_updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Match_Note_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Match_Note" ADD CONSTRAINT "Match_Note_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "Match"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
