-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "dt_of_birth" TIMESTAMP(3);
ALTER TABLE "Profile" ADD COLUMN     "first_name" STRING;
ALTER TABLE "Profile" ADD COLUMN     "last_name" STRING;
ALTER TABLE "Profile" ADD COLUMN     "role" STRING NOT NULL DEFAULT E'VOLUNTEER';
ALTER TABLE "Profile" ALTER COLUMN "dt_created" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Profile" ALTER COLUMN "dt_updated" SET DEFAULT CURRENT_TIMESTAMP;
